version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-security-and-maintenance:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /packages/core
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
